language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - git clone https://github.com/dominno/django-moderation.git 
  - cd django-moderation
  - python setup.py install
  - cd ..
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - coverage run --source=rest_onigiri,directory manage.py test
after_success: coveralls
